export enum UserActionConstants {
  ADD_USERS = 'ADD_USERS',
  ADD_USERS_SUCCESS = 'ADD_USERS_SUCCESS',
  ADD_USERS_ERROR = 'ADD_USERS_ADD_USERS_ERROR',
  DELETE_USER = 'DELETE_USER',
  RESET_USERS = 'RESET_USERS',
  CLOSE_INFO = 'CLOSE_INFO',
}
